// CreatorDB niche name → ID resolver. Loads static mapping files generated by
// scripts/fetch-creatordb-niches.ts and resolves user-typed niche names to
// CreatorDB taxonomy IDs for use in search filters.

import { distance } from 'fastest-levenshtein'

interface NicheEntry {
  id: string
  name: string
  category: string
  channelCount: number
}

type NicheMap = Record<string, NicheEntry[]>

export interface NicheMatchExact {
  term: string
  translatedFrom?: string // original non-English term if translated
  ids: string[]
}

export interface NicheMatchFuzzy {
  term: string
  translatedFrom?: string // original non-English term if translated
  matchedName: string
  score: number
  ids: string[]
}

export interface NicheUnmatched {
  term: string
  suggestions: string[]
}

export interface NicheResolveResult {
  matched: NicheMatchExact[]
  fuzzyMatched: NicheMatchFuzzy[]
  unmatched: NicheUnmatched[]
  ids: string[]
}

// ── Mapping cache ──────────────────────────────────────────────────────────────

const mapCache: Record<string, NicheMap> = {}

function loadMap(platform: string): NicheMap {
  if (mapCache[platform]) return mapCache[platform]
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const data = require(`../data/creatordb-niches/${platform}.json`)
    mapCache[platform] = data
    return data
  } catch {
    console.warn(`[creatordb-niches] No mapping file for ${platform}`)
    mapCache[platform] = {}
    return {}
  }
}

// Exposed for tests
export function _loadMap(platform: string): NicheMap {
  return loadMap(platform)
}

// ── Normalization ──────────────────────────────────────────────────────────────

function normalizeKey(name: string): string {
  return name
    .toLowerCase()
    .trim()
    // Strip ASCII punctuation but keep letters, digits, spaces, and non-Latin scripts
    .replace(/[\u0021-\u002F\u003A-\u0040\u005B-\u0060\u007B-\u007E]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

// ── Similarity (Levenshtein-based, scaled 0–100) ─────────────────────────────

function similarity(a: string, b: string): number {
  const maxLen = Math.max(a.length, b.length)
  if (maxLen === 0) return 100
  return Math.round((1 - distance(a, b) / maxLen) * 100)
}

// ── Non-English → English translation ──────────────────────────────────────────
// Static table for Chinese (the app's second language) and other common
// languages. Checked before fuzzy matching so "美食" resolves to "Food" etc.

// Use a Map to avoid duplicate key errors with shared CJK characters
const NICHE_TRANSLATIONS = new Map<string, string>([
  // Chinese (Simplified)
  ['美食', 'food'], ['食物', 'food'], ['美妆', 'beauty'], ['化妆', 'makeup'],
  ['护肤', 'skincare'], ['时尚', 'fashion'], ['穿搭', 'fashion'], ['旅行', 'travel'],
  ['旅游', 'travel'], ['健身', 'fitness'], ['运动', 'sports'], ['游戏', 'gaming'],
  ['音乐', 'music'], ['舞蹈', 'dance'], ['搞笑', 'comedy'], ['教育', 'education'],
  ['科技', 'tech'], ['生活', 'lifestyle'], ['摄影', 'photography'], ['宠物', 'pets'],
  ['育儿', 'parenting'], ['金融', 'finance'], ['投资', 'finance'], ['商业', 'business'],
  ['创业', 'business'], ['科学', 'science'], ['汽车', 'automotive'], ['户外', 'outdoors'],
  ['瑜伽', 'yoga'], ['家居', 'home decor'], ['园艺', 'gardening'], ['动漫', 'anime'],
  ['电影', 'movies'], ['阅读', 'book'], ['奢侈品', 'luxury'], ['潮流', 'streetwear'],
  ['健康', 'health'], ['心理健康', 'mental health'], ['露营', 'camping'],
  ['美甲', 'nail art'], ['纹身', 'tattoo'], ['烹饪', 'cooking'], ['烘焙', 'baking'],
  ['手工', 'diy'], ['艺术', 'art'], ['娱乐', 'entertainment'], ['体育', 'sports'],
  ['足球', 'football'], ['篮球', 'basketball'], ['减肥', 'weight loss'],
  ['养生', 'wellness'], ['房地产', 'real estate'], ['建筑', 'architecture'],
  ['环保', 'sustainability'], ['母婴', 'parenting'], ['数码', 'tech'],
  ['发型', 'hair'], ['医美', 'beauty'], ['彩妆', 'makeup'], ['香水', 'perfume'],
  ['珠宝', 'jewelry'], ['手表', 'watches'], ['鞋子', 'shoes'], ['包包', 'bags'],
  ['家装', 'interior design'], ['装修', 'interior design'], ['绘画', 'painting'],
  ['书法', 'calligraphy'], ['设计', 'design'], ['编程', 'coding'], ['人工智能', 'ai'],
  ['加密货币', 'cryptocurrency'], ['区块链', 'blockchain'], ['电商', 'ecommerce'],
  ['直播', 'livestream'], ['网红', 'influencer'], ['带货', 'shopping'],
  // Chinese (Traditional) — only keys that differ from Simplified
  ['美妝', 'beauty'], ['化妝', 'makeup'], ['護膚', 'skincare'],
  ['時尚', 'fashion'], ['旅遊', 'travel'], ['運動', 'sports'],
  ['遊戲', 'gaming'], ['攝影', 'photography'], ['寵物', 'pets'], ['科學', 'science'],
  ['戶外', 'outdoors'], ['動漫', 'anime'], ['電影', 'movies'], ['閱讀', 'book'],
  ['烹飪', 'cooking'], ['園藝', 'gardening'], ['環保', 'sustainability'],
  // Japanese
  ['グルメ', 'food'], ['美容', 'beauty'], ['ファッション', 'fashion'],
  ['フィットネス', 'fitness'], ['ゲーム', 'gaming'],
  ['音楽', 'music'], ['ダンス', 'dance'], ['ペット', 'pets'],
  ['料理', 'cooking'], ['スポーツ', 'sports'], ['アニメ', 'anime'],
  // Korean
  ['뷰티', 'beauty'], ['패션', 'fashion'], ['여행', 'travel'], ['음식', 'food'],
  ['요리', 'cooking'], ['게임', 'gaming'], ['음악', 'music'], ['피트니스', 'fitness'],
  ['댄스', 'dance'], ['교육', 'education'], ['건강', 'health'],
  // Spanish
  ['comida', 'food'], ['belleza', 'beauty'], ['moda', 'fashion'], ['viaje', 'travel'],
  ['viajes', 'travel'], ['cocina', 'cooking'], ['deporte', 'sports'],
  ['deportes', 'sports'], ['salud', 'health'], ['tecnología', 'tech'],
  ['tecnologia', 'tech'], ['educación', 'education'], ['educacion', 'education'],
  ['mascotas', 'pets'], ['música', 'music'], ['musica', 'music'],
  // French
  ['nourriture', 'food'], ['beauté', 'beauty'], ['cuisine', 'cooking'],
  ['voyage', 'travel'], ['voyages', 'travel'], ['santé', 'health'],
  ['éducation', 'education'], ['animaux', 'pets'], ['musique', 'music'],
  ['danse', 'dance'], ['jeux', 'gaming'], ['sport', 'sports'],
  // Portuguese
  ['beleza', 'beauty'], ['cozinha', 'cooking'],
  ['viagem', 'travel'], ['saúde', 'health'], ['esporte', 'sports'],
  ['esportes', 'sports'], ['educação', 'education'], ['animais', 'pets'],
])

function hasNonLatinChars(text: string): boolean {
  return /[^\u0000-\u024F\s]/.test(text)
}

export function translateTerm(term: string): string | null {
  const trimmed = term.trim()
  // Direct lookup
  if (NICHE_TRANSLATIONS.has(trimmed)) return NICHE_TRANSLATIONS.get(trimmed)!
  // Lowercase lookup (for Latin-script translations like Spanish/French)
  const lower = trimmed.toLowerCase()
  if (NICHE_TRANSLATIONS.has(lower)) return NICHE_TRANSLATIONS.get(lower)!
  return null
}

// ── Resolver ───────────────────────────────────────────────────────────────────

const FUZZY_THRESHOLD = 80
const MAX_SUGGESTIONS = 3
const MAX_IDS = 100

export function resolveNiches(
  platform: string,
  userInput: string,
): NicheResolveResult {
  const map = loadMap(platform)
  const allNames = Object.keys(map)

  // Split on commas, semicolons, " and ", Chinese comma/pause mark
  const terms = userInput
    .split(/[,;，、]|\band\b/i)
    .map((t) => t.trim())
    .filter(Boolean)

  const matched: NicheMatchExact[] = []
  const fuzzyMatched: NicheMatchFuzzy[] = []
  const unmatched: NicheUnmatched[] = []
  const allIds = new Set<string>()

  for (const rawTerm of terms) {
    // Translate non-English terms before matching
    const translated = translateTerm(rawTerm)
    const effectiveTerm = translated ?? rawTerm
    const key = normalizeKey(effectiveTerm)
    if (!key) continue

    // Exact match
    if (map[key]) {
      const ids = map[key].map((e) => e.id)
      matched.push({
        term: effectiveTerm,
        ...(translated ? { translatedFrom: rawTerm } : {}),
        ids,
      })
      for (const id of ids) allIds.add(id)
      continue
    }

    // Fuzzy match — compare against all names
    let bestName: string | null = null
    let bestScore = 0
    let bestChannelCount = 0

    for (const candidate of allNames) {
      const score = similarity(key, candidate)
      if (score >= FUZZY_THRESHOLD) {
        const topCount = map[candidate][0]?.channelCount ?? 0
        if (
          score > bestScore ||
          (score === bestScore && topCount > bestChannelCount)
        ) {
          bestScore = score
          bestName = candidate
          bestChannelCount = topCount
        }
      }
    }

    if (bestName) {
      const ids = map[bestName].map((e) => e.id)
      fuzzyMatched.push({
        term: effectiveTerm,
        ...(translated ? { translatedFrom: rawTerm } : {}),
        matchedName: map[bestName][0].name, // original casing
        score: bestScore,
        ids,
      })
      for (const id of ids) allIds.add(id)
      continue
    }

    // Unmatched — find top 3 closest as suggestions
    const scored = allNames
      .map((name) => ({ name: map[name][0].name, score: similarity(key, name) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, MAX_SUGGESTIONS)
    unmatched.push({
      term: rawTerm,
      suggestions: scored.map((s) => s.name),
    })
  }

  // Deduplicate and cap at 100 IDs
  let ids = [...allIds]
  if (ids.length > MAX_IDS) {
    // Keep top 100 by channelCount — need to look up counts
    const entries = new Map<string, number>()
    for (const name of allNames) {
      for (const entry of map[name]) {
        entries.set(entry.id, entry.channelCount)
      }
    }
    ids = ids
      .sort((a, b) => (entries.get(b) ?? 0) - (entries.get(a) ?? 0))
      .slice(0, MAX_IDS)
    console.warn(
      `[creatordb-niches] ${allIds.size} niche IDs exceed the 100 cap; keeping top ${MAX_IDS} by channelCount`,
    )
  }

  return { matched, fuzzyMatched, unmatched, ids }
}
